name: Build and Deploy Android App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: List directory structure
        run: find . -type f -name "*.gradle*" | sort
      
      - name: Check Gradle version
        run: |
          cd cg_mobile_app
          if [ -f "./gradlew" ]; then
            ./gradlew --version
          else
            echo "Gradlew file not found!"
            ls -la
          fi
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: cg_mobile_app
      
      - name: Update compileSdk in build.gradle.kts
        run: |
          if [ -f "app/build.gradle.kts" ]; then
            sed -i 's/compileSdk = 35/compileSdk = 34/g' app/build.gradle.kts
            echo "Modified build.gradle.kts:"
            cat app/build.gradle.kts
          else
            echo "app/build.gradle.kts not found!"
            find . -name "build.gradle*" | xargs cat
          fi
        working-directory: cg_mobile_app
      
      - name: Clean project with debug
        run: ./gradlew clean --info
        working-directory: cg_mobile_app
      
      - name: Show environment info
        run: |
          java -version
          echo "ANDROID_HOME: $ANDROID_HOME"
          ls -la $ANDROID_HOME/platforms
      
      - name: Build debug APK with full debug output
        run: ./gradlew assembleDebug --stacktrace --debug
        working-directory: cg_mobile_app
      
      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: cg_mobile_app/app/build/reports/
          retention-days: 7
      
      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: cg_mobile_app/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
