name: Deploy to Firebase App Distribution

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./cg_mobile_app/gradlew
      
      - name: Build with Gradle
        working-directory: ./cg_mobile_app
        run: ./gradlew assembleRelease
      
      - name: Sign APK
        working-directory: ./cg_mobile_app
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          # Copy unsigned APK
          cp ./app/build/outputs/apk/release/app-release-unsigned.apk ./app/build/outputs/apk/release/app-release.apk

          # Sign the APK using jarsigner
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore ./keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            ./app/build/outputs/apk/release/app-release.apk \
            ${{ secrets.KEY_ALIAS }}

          # Verify the APK signature
          apksigner verify --verbose ./app/build/outputs/apk/release/app-release.apk
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./cg_mobile_app/app/build/outputs/apk/release/app-release.apk
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: .
      
      - name: List downloaded files
        run: ls -la
      
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          groups: testers
          file: app-release.apk
          releaseNotes: "New version available for testing"
