name: Deploy to Firebase App Distribution

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./cg_mobile_app/gradlew
      
      - name: Build with Gradle
        working-directory: ./cg_mobile_app
        run: ./gradlew assembleRelease
      
      - name: List built APK files
        run: ls -la ./cg_mobile_app/app/build/outputs/apk/release/
      
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./cg_mobile_app/app/build/outputs/apk/release/app-release.apk
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: app-release
      
      - name: List downloaded files
        run: ls -la
      
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          groups: testers
          file: app-release/app-release.apk  # Correct path to the APK
          releaseNotes: "New version available for testing"
