name: Deploy to Firebase

on:
  push:
    branches: [ main ]  # Change to your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: cg_mobile_app
      
      - name: Build with Gradle (with verbose output)
        run: ./gradlew build --stacktrace --info
        working-directory: cg_mobile_app
      
      - name: Check if release directory exists
        run: mkdir -p app/release
        working-directory: cg_mobile_app
      
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace --info
        working-directory: cg_mobile_app
      
      - name: Debug - List all directories
        run: find . -type d | sort
        working-directory: cg_mobile_app
      
      - name: Debug - List all APK files
        run: find . -name "*.apk"
        working-directory: cg_mobile_app
      
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: cg_mobile_app/app/build/outputs/apk/release/app-release.apk  # Changed path to standard output location
