name: Deploy to Firebase App Distribution

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./cg_mobile_app/gradlew
      
      - name: Build with Gradle
        working-directory: ./cg_mobile_app
        run: ./gradlew assembleRelease
      
      - name: Debug - List APK files
        run: find cg_mobile_app -name "*.apk" -type f
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: cg_mobile_app/app/release/*.apk
          if-no-files-found: error
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: app-release
      
      - name: List downloaded files
        run: ls -la app-release/
      
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          groups: testers
          file: app-release/*.apk
