name: Deploy to Firebase

on:
  push:
    branches: [ main ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: cg_mobile_app  # Adjust if this is not correct
      
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: cg_mobile_app  # Adjust if this is not correct
      
      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: cg_mobile_app  # Adjust if this is not correct
      
      - name: Debug - List APK files
        run: Build Release APK
        working-directory: cg_mobile_app  # Adjust if this is not correct
      
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: cg_mobile_app/app/release/app-release.apk  # Using your provided path
