name: Build and Deploy Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: cg_mobile_app
      
      - name: Update compileSdk in build.gradle.kts
        run: |
          sed -i 's/compileSdk = 35/compileSdk = 34/g' app/build.gradle.kts
        working-directory: cg_mobile_app
      
      - name: Clean project
        run: ./gradlew clean
        working-directory: cg_mobile_app
      
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
        working-directory: cg_mobile_app
      
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: cg_mobile_app/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
      
      - name: Sign Release APK
        run: ./gradlew assembleRelease
        working-directory: cg_mobile_app
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      
      - name: Upload release APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        if: success()
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: cg_mobile_app/app/build/outputs/apk/release/app-release.apk
          releaseNotes: "Automated build from GitHub Actions"
