name: Build and Deploy Android App 

on: 
  push: 
    branches: [ main ] 
  workflow_dispatch: 

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
        with: 
          fetch-depth: 0 
          
      - name: Set up JDK 17 
        uses: actions/setup-java@v3 
        with: 
          java-version: '17' 
          distribution: 'temurin' 
          cache: gradle 
          
      - name: Setup Android SDK 
        uses: android-actions/setup-android@v2 
        
      - name: Display project structure
        run: |
          echo "Project Root:"
          ls -la
          echo "Looking for Android project files:"
          find . -name "build.gradle*" -o -name "gradlew" -o -name "AndroidManifest.xml" | sort
      
      - name: Grant execute permission for gradlew 
        run: | 
          find . -name "gradlew" -exec chmod +x {} \; 
          
      - name: Configure Gradle memory settings
        run: |
          APP_DIR=$(find . -name "gradlew" | sed 's|/gradlew||' | head -n 1)
          cd $APP_DIR
          mkdir -p gradle
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError" > gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "org.gradle.caching=true" >> gradle.properties
          echo "org.gradle.logging.level=info" >> gradle.properties
          
      - name: Show build files content
        run: |
          echo "=== Main build.gradle ==="
          find . -name "build.gradle" -not -path "*/app/*" -exec cat {} \;
          echo "=== App build.gradle ==="
          find . -path "*/app/build.gradle*" -exec cat {} \;
          echo "=== settings.gradle ==="
          find . -name "settings.gradle*" -exec cat {} \;
          
      - name: Fix compileSdk issues
        run: |
          find . -name "build.gradle*" -exec sed -i 's/compileSdk[ ]*=[ ]*35/compileSdk = 34/g' {} \;
          find . -name "build.gradle*" -exec sed -i 's/compileSdkVersion[ ]*35/compileSdkVersion 34/g' {} \;
          
      - name: List available Android SDK platforms
        run: |
          ls -la $ANDROID_HOME/platforms
          
      - name: Clean with diagnostic output
        run: | 
          APP_DIR=$(find . -name "gradlew" | sed 's|/gradlew||' | head -n 1)
          cd $APP_DIR
          ./gradlew clean --debug > clean_log.txt 2>&1 || (cat clean_log.txt && exit 1)
          
      - name: Build debug APK with verbose logging
        run: | 
          APP_DIR=$(find . -name "gradlew" | sed 's|/gradlew||' | head -n 1)
          cd $APP_DIR
          ./gradlew tasks --all > available_tasks.txt
          echo "====== Available Gradle Tasks ======"
          cat available_tasks.txt
          # Try build with multiple combinations to isolate the issue
          echo "====== First attempt: assembleDebug ======"
          ./gradlew assembleDebug --debug > build_log.txt 2>&1 || true
          if [ ! -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "====== Second attempt: app:assembleDebug ======"
            ./gradlew app:assembleDebug --debug >> build_log.txt 2>&1 || true
          fi
          # Try a simpler task to get more info
          if [ ! -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "====== Attempting simple compile ======"
            ./gradlew compileDebugJavaWithJavac --debug >> build_log.txt 2>&1 || true
          fi
          
      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            **/build_log.txt
            **/clean_log.txt
            **/available_tasks.txt
            **/build/reports/**
          retention-days: 7
          
      - name: Check if APK was generated
        run: |
          find . -name "*.apk"
          
      - name: Upload debug APK 
        if: success() 
        uses: actions/upload-artifact@v4 
        with: 
          name: app-debug 
          path: | 
            **/build/outputs/apk/debug/*.apk 
          retention-days: 7
